export const CREATE_GAME_REQUEST = 'CREATE_GAME_REQUEST';
export const CREATE_GAME_SUCCESS = 'CREATE_GAME_SUCCESS';
export const CREATE_GAME_FAILURE = 'CREATE_GAME_FAILURE';

export const VERIFY_PIN_REQUEST = 'VERIFY_PIN_REQUEST';
export const VERIFY_PIN_SUCCESS = 'VERIFY_PIN_SUCCESS';
export const VERIFY_PIN_FAILURE = 'VERIFY_PIN_FAILURE';

export const OPPONENT_JOINED = 'OPPONENT_JOINED';
export const GAME_DATA_RECEIVED = 'GAME_DATA_RECEIVED';
export const GAME_START = 'GAME_START';
export const PLAY = 'PLAY';
export const GAME_END = 'GAME_END';

export const REPLAY = 'REPLAY';
